In [77]:
import numpy as np
import cv2 as cv


In [65]:
arr = np.random.randint(10, size=(5,5,3))
arr

array([[[5, 0, 7],
        [8, 7, 8],
        [4, 7, 0],
        [2, 1, 3],
        [2, 3, 1]],

       [[7, 5, 1],
        [9, 2, 1],
        [2, 4, 7],
        [6, 5, 3],
        [8, 1, 2]],

       [[4, 5, 2],
        [7, 0, 9],
        [3, 8, 4],
        [8, 2, 2],
        [1, 3, 4]],

       [[8, 7, 4],
        [9, 6, 7],
        [8, 5, 2],
        [3, 5, 2],
        [7, 1, 2]],

       [[7, 4, 2],
        [9, 3, 9],
        [2, 4, 6],
        [5, 6, 1],
        [7, 1, 0]]])

In [11]:
arr2 = np.zeros((500,500,3), dtype='uint8')
arr2[0].shape

(500, 3)

In [76]:
arr[:,:,0]

array([[5, 8, 4, 2, 2],
       [7, 9, 2, 6, 8],
       [4, 7, 3, 8, 1],
       [8, 9, 8, 3, 7],
       [7, 9, 2, 5, 7]])

In [19]:
to = np.random.randint(10, size=(2,4))
to

array([[2, 0, 4, 5],
       [1, 2, 6, 3]])

In [27]:
to[:,0]

array([2, 1])

In [84]:
img = cv.imread("images/cat.jpg")

# cv.imshow("Image", img[:,:,0])
cv.imshow("Image", img)
cv.waitKey(0)

119

: 